export const SET_TREE_DATA = 'SET_TREE_DATA';
export const SET_FILTER_DATA = 'SET_FILTER_DATA';
export const SET_SELECTED_FILES = 'SET_SELECTED_FILES';
export const SET_COPY_FILES = 'SET_COPY_FILES';
export const SET_IS_COPY = 'SET_IS_COPY';
export const SET_CONTEXT_MENU_VISIBLE = 'SET_CONTEXT_MENU_VISIBLE';
export const SET_CONTEXT_MENU_POSITION = 'SET_CONTEXT_MENU_POSITION';
export const SET_SELECTED_FOLDER_SUB_LIST = 'SET_SELECTED_FOLDER_SUB_LIST';
export const SET_FILE_CONTENT = 'SET_FILE_CONTENT';
export const SET_VISIBLE_DIALOG_CREATE_FOLDER =
  'SET_VISIBLE_DIALOG_CREATE_FOLDER';
export const SET_FILE_CONTENT_VISI = 'SET_FILE_CONTENT_VISI'
export const SET_VISIBLE_DIALOG_RENAME = 'SET_VISIBLE_DIALOG_RENAME';
